main.exe: bst.o item.o  main.o stack.o
	gcc bst.o item.o main.o stack.o -o main.exe
	
bst.o:bst.c
	gcc -c bst.c
	
item.o:item.c
	gcc -c item.c
	

	
main.o:main.c
	gcc -c main.c

stack.o:stack.c
	gcc -c stack.c
